#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^#
####################### Define Grid Generation Functions ########################
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^#
"""
    find_lik_asymptote(data::DataStr,theta::Vector{Float64},covar::Array{Float64},delta::Float64)
Function to determine the approximate values of θ that result in the start of the asymptote of the likelihood function.

---
Keyword arguments
* `data::DataStr` Struct containing the computer simulator and experimental data.
* `theta::Vector{Float64}` Maximum likelihood estimates for θ.
* `covar::Array{Float64}` Maximum likelihood estimate for the covariance matrix of the data model.
* `delta::Float64` Step size in θ.

---
Returns
* `upper_bounds::Vector{Float64}` Vector of θ values greater than their MLE that correspond to the start of the asymptotic behavior of the likelihood function.
* `lower_bounds::Vector{Float64}` Vector of θ values lesser than their MLE that correspond to the start of the asymptotic behavior of the likelihood function.

---
Details
"""
function find_lik_asymptote(data::DataStr,theta::Vector{Float64},covar::Array{Float64},delta::Float64)
    response_mle = predict_y_all(theta)
    max_lik = prod(pdf(MvNormal(response_mle,covar),data.exp.y))[1]
    upper_bounds = Vector{Float64}(undef,length(theta))
    lower_bounds = similar(upper_bounds)

    for i in eachindex(theta)
        epsilon = 10
        
        new_lik = copy(max_lik)
        theta_delta = copy(theta)
        while((epsilon > 1e-10) | (new_lik > (0.5*max_lik)))
            old_lik = copy(new_lik)
            theta_delta[i] += delta
            response = predict_y_all(theta_delta)
            new_lik = prod(pdf(MvNormal(response,covar),data.exp.y))[1]
            epsilon = abs(new_lik - old_pdf)
            upper_bounds[i] = theta_delta[i]
        end

        epsilon = 10
        new_lik = copy(max_lik)
        theta_delta = copy(theta)
        while((epsilon > 1e-10) | new_lik > (0.5*max_lik))
            old_lik = copy(new_lik)
            theta_delta[i] -= delta
            response = predict_y_all(theta_delta)
            new_lik = prod(pdf(MvNormal(response,covar),data.exp.y))[1]
            lower_bounds[i] = theta_delta[i]
        end
    end
    return upper_bounds,lower_bounds
end

"""
    format_doe(doe::Array{Float64},data::DataStr,nobs::Int,nx::Int,ntheta::Int)
Function to format the raw DOE of θ generated by `get_full_fact` to include settings of x variables.

---
Keyword arguments
* `doe::Array{Float64}` DOE to be edited.
* `data::DataStr` Strucdt containing computer simulator and experimental data.
* `nobs::Int` The number of x settings for the computer simulator and experimental data.
* `nx::Int` The number of independent control variables.
* `ntheta::Int` The number of unknown independent variables in the computer simulator, θ.

---
Returns
* `full_doe::Array{Float64}` The formatted DOE.
"""
function format_doe(doe::Array{Float64},data::DataStr,nobs::Int,nx::Int,ntheta::Int)
    num_design = size(doe)[1]
    num_row = num_design*nobs
    full_doe = Array{Float64}(undef,num_row,(nx+ntheta))
    for i in 1:num_design
        start = (i-1)*nobs + 1
        stop = i*nobs
        full_doe[start:stop,1:nx] = data.exp.x
        full_doe[start:stop,(nx+1):(nx+ntheta)] = repeat(doe[i,:]',nobs,1)
    end
    return full_doe
end

"""
    get_full_fact(n::Int,ntheta::Int,bounds:;Tuple{Vector{Float64}})
Function to generate a full factorial, uniform grid, design of experiments for θ, in the bounds specified.

---
Keyword arguments
* `n::Int` The number of grid points to use per dimension of θ.
* `ntheta::Int` The number of unknown independent variables in the computer simulator.
* `bounds::Tuple{Vector{Float64}}` A Tuple of two Vectors, each having a length of `ntheta`, that specify the bounds for each θ. The first Vector in the Tuple contains the upper bounds and the second Vector contains the lower bounds.

---
Returns
* `doe::Array{Float64}` design of experiments.
"""
function get_full_fact(n::Int,ntheta::Int,bounds::Tuple{Vector{Float64}})
    fact_vals = Array{Float64}(undef,n,ntheta)
    for theta in 1:ntheta
        fact_vals[:,theta,dim] = collecct(range(bounds[2][theta],bounds[1][theta],length=n))
    end
    doe = Array{Float64}(undef,n^dim,dim)
    for j in axes(doe)[2]
        reps = repeat(fact_vals[:,j],inner=n^(j-1),outer=n^(size(doe)[2]-(j)))
        doe[:,j] .= reps
    end
    return doe
end

"""
    generate_sample_grid(n::Int,data::DataStr,nx::Int,ntheta::Int,delta::Float64=1e-3,model=model)
Function to generate the sampling grid for the griddy gibbs approach.

---
Keyword arguments
* `n::Int` The number of grid points per dimension of θ.
* `data::DataStr` Struct containing the computer simulator and experimental data.
* `nx::Int` The number of x dimensions.
* `ntheta::Int` The number of θ dimensions.
* `delta::Float64` The step-size to use for the asymptote calculation algorithm, default value of 1E-3.
* `model` The surrogate model used for calculating the bounds. The default model is the vectorized Gaussian process model generated by this package.

---
Returns
* `doe::Array{Float64}` The sampling grid for θ to use for the griddy Gibbs sampler.

---
Details
This function first solves for the maximum likelihood values of the θ parameters and the covariance matrix.
After the MLE are solved, the approximate asymtptotes of the likelihood function are calculated.
During this step, the θ values closest to the θ MLEs that generate asymptotic likelihood values are calculated.
With these bounds for θ solved, a full factorial, uniform grid DOE is generated over the bounds of θ.
"""
function generate_sample_grid(n::Int,data::DataStr,nx::Int,ntheta::Int,delta::Float64=1e-3,model=model)
    theta_mle,covar_mle = get_mle(data,nx,ntheta)
    bounds = find_lik_asymptote(data,theta_mle,covar_mle,delta)
    doe = get_full_fact(n,ntheta,bounds)
    return doe
end